### ISSUE TITLE
Addon not correctly registering workshop requirement

### ISSUE THREAD

**Issue by Xalaxis** [menof36go/ttt2-error-grenade#1]
Hi!

This addon does not seem to be properly registering it's workshop requirement, so instead of the error textures getting downloaded from the Steam workshop, they are downloaded directly from the server itself (incredibly slowly).

**Comment by menof36go** [comment]
I am currently busy with university, but feel free to make a pull request

**Comment by mexikoedi** [comment]
> Hi!
> 
> This addon does not seem to be properly registering it's workshop requirement, so instead of the error textures getting downloaded from the Steam workshop, they are downloaded directly from the server itself (incredibly slowly).

Can't reproduce this issue. The code seems fine. Make sure that this addon is in the Server collection and that everyone has downloaded it. If not it will take some time because Garry's Mod has a restricted download speed.
